name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: quality
          pixi-version: v0.47.0
          cache: false
          locked: false

      - name: Initialize pixi
        run: |
          pixi install

      - name: Check formatting with black
        run: pixi run -e quality format --check --diff .

      - name: Check imports with pyflakes
        run: pixi run -e quality lint

  testing:
    needs: code-quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [py39, py310, py311, py312, py313]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: ${{ matrix.environment }}
          pixi-version: v0.47.0
          cache: false
          locked: false

      - name: Setup test environment with Pixi
        run: |
          pixi install

      - name: Test snakedeploy
        run: |
          pixi run -e ${{matrix.environment}} test
